# Uncomment the next line to define a global platform for your project
# platform :ios, ‘8.0’

project 'DR_NewMedia.project'

inhibit_all_warnings!

target 'DR_NewMedia' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DR_NewMedia
pod ‘Masonry’

pod ‘SDWebImage’

pod 'MBProgressHUD'

pod 'LBXScan/LBXZXing','~> 2.0'
pod 'LBXScan/UI','~> 2.0'

# U-Share SDK UI模块（分享面板，建议添加）
pod ‘UMengUShare/UI’

# 集成微信(精简版0.2M)
pod ‘UMengUShare/Social/ReducedWeChat'

# 集成QQ(精简版0.5M)
pod ‘UMengUShare/Social/ReducedQQ'

# 集成新浪微博(精简版1M)
pod ‘UMengUShare/Social/ReducedSina'

# 集成支付宝
pod ‘UMengUShare/Social/AlipayShare'

# 集成豆瓣
pod ‘UMengUShare/Social/Douban'


end
